"""Change relations, add profile

Revision ID: 6153e751dbe2
Revises: 39a9ba1a9fa9
Create Date: 2023-11-01 23:37:39.446321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6153e751dbe2'
down_revision: Union[str, None] = '39a9ba1a9fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('full_nm', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('user', 'username')
    op.drop_table('profile')
    # ### end Alembic commands ###
