"""Remove disabled field

Revision ID: 71a865d9bfe9
Revises: db9a8fbae8ec
Create Date: 2023-11-01 22:34:57.148227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a865d9bfe9'
down_revision: Union[str, None] = 'db9a8fbae8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
