"""Add token entity

Revision ID: 790dfab0ee7d
Revises: 9dccd0b8cb7a
Create Date: 2023-10-26 01:14:29.899703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790dfab0ee7d'
down_revision: Union[str, None] = '9dccd0b8cb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name='token_pk'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_token_access_token'), 'token', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_access_token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
