"""Add relation to profile and user

Revision ID: 8bc2e876ad24
Revises: 6153e751dbe2
Create Date: 2023-11-01 23:53:26.379938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc2e876ad24'
down_revision: Union[str, None] = '6153e751dbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('organisation_user_id_fkey', 'organisation', type_='foreignkey')
    op.create_foreign_key(None, 'organisation', 'profile', ['profile_id'], ['id'])
    op.drop_column('organisation', 'user_id')
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_constraint('social_account_user_id_fkey', 'social_account', type_='foreignkey')
    op.create_foreign_key(None, 'social_account', 'profile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_account', type_='foreignkey')
    op.create_foreign_key('social_account_user_id_fkey', 'social_account', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    op.add_column('organisation', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.create_foreign_key('organisation_user_id_fkey', 'organisation', 'user', ['user_id'], ['id'])
    op.drop_column('organisation', 'profile_id')
    # ### end Alembic commands ###
