"""Remove key field

Revision ID: db9a8fbae8ec
Revises: e6bfc7839bb8
Create Date: 2023-11-01 21:57:49.180537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9a8fbae8ec'
down_revision: Union[str, None] = 'e6bfc7839bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
